### ISSUE TITLE
Database resets when relogging?

### ISSUE THREAD

**Issue by toomas-siim** [2009scape/Singleplayer-Edition-Windows#20]
Hi, as soon as i log out and in again im back at the character creation page.

**Comment by Skyrim2Installer** [comment]
the only thing i could think of is edit the batch file to xcopy the location of where the savegame files are kept to a new folder called saves. Then xcopy them back in when you launch the main menu script again

**Comment by Ceikry** [comment]
saves have nothing to do with the database.
if your game isn't saving it's user error. 
many people have reported this in our discord and it was different varieties of user error practically every time.

**Comment by Ceikry** [comment]
(with the most common issue being using the wrong version of java - this project requires java 11 currently.)

**Comment by Ceikry** [comment]
Also, this repo is deprecated, we have moved to gitlab since early 2021, and singleplayer itself moved recently: https://gitlab.com/2009scape/singleplayer/windows)

**Comment by Skyrim2Installer** [comment]
Thanks for responce, i was just messing with my JDK file location so that actually was the fix thank you

**Comment by Skyrim2Installer** [comment]
amazing game too love this and would love to help in the future free of charge haha

**Comment by Ceikry** [comment]
Naturally. 
Everyone who works on this project is a volunteer.
Check out the updated version on gitlab.
